name:                reflective-minimal
version:             0.1.0.0
github:              "githubuser/reflective-minimal"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/system-f-bin#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- QuickCheck
- profunctors
- data-default
- mtl
- logict
- template-haskell
- directory
- leancheck
- free

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists

library:
  source-dirs: src

executables:
  reflective-minimal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflective-minimal

  json-exe:
    main:                Main.hs
    source-dirs:         json-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflective-minimal

  package-json-exe:
    main:                Main.hs
    source-dirs:         package-json-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflective-minimal

tests:
  reflective-minimal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - reflective-minimal
